//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHenryTenorio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pacientesmvcEntities : DbContext
    {
        public pacientesmvcEntities()
            : base("name=pacientesmvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Medicina> Medicina { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Prescripcion> Prescripcion { get; set; }
    
        public virtual ObjectResult<F_Reporte_Medicinas_Result> F_Reporte_Medicinas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<F_Reporte_Medicinas_Result>("F_Reporte_Medicinas");
        }
    }
}
