//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHenryTenorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion
    {
        public int PrescripcionID { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public Nullable<int> MedicinaID { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual Medicina Medicina { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
